version: '3.3'

services:
  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
  powerflow:
    build:
      context: '.'
      dockerfile: './powerflow.Dockerfile'
    volumes:
      - ./powerflow:/powerflow
    command: bash -c "cd powerflow && 
                      make init &&
                      cd .. &&
                      /powerflow/powerflow/bin/python3 /powerflow/runPF.py --ext_port 7070"
    command:          tail -F dfsdfödslk
    ports:
      - 7070:8000
  pv_centralized:
    build:
      context: '.'
      dockerfile: './pv_centralized.Dockerfile'
    volumes:
      - ./pv_centralized:/pv_centralized
    command: bash -c "cd pv_centralized && 
                      make init &&
                      cd .. &&
                      /pv_centralized/covee/bin/python3 /pv_centralized/Control_main.py --ext_port 7071"
    command:          tail -F dfsdfödslk
    ports:
      - 7071:8000

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"